language: node_js
node_js:
- 'node'

# safelist
branches:
  only:
    - master
deploy:
  provider: npm
  email: "ycuobu@gmail.com"
  api_key:
    secure: 7yJubOolWxVXEg7LBJoyx8SxURJbBl/SriNpXZV1bACLG6Rb146ps/XmAARr4FoosDzKB2erhbsZYsRwHP+cRn794tUbjqN6tNYAMvFgBjFhhCozRjDS0xq2H4LWnqnct911tedoWebYEpX1YVnB78PzNTJ3RWrMBk++BcQONLtge+H32cHSDbkWOlM5GS+FJnKtPUuOiuxteJiKEYTu61ovVaiQQcE69zQQGb10W9fUXs1ZNNwPxBTtYflywno2/O8+8oS+h2OYQnNNvluAqtm7/iZ8w7P1XkCgYBGvuyrPyhUptzxOer59U0lHhQoISGhOLPkDrPI2+N7a4l20tFtCBmm6SQT5NsK1M5zeTsbYw4XpCIatGP11FOnybO9a6Lh/lCNl1MzOGRhodI2134m5INGMUziwEU6RmEP5PRREbMV2oZhOq5GSRvoURTXSVEb73te04xX031pyJnmn34kfub0h1uUnGfL2uGdl9iOBFJ+sQoXjIIMQC+uXLvXYIoPRHVA4x+VxzGviImGXn3LlcyQSo1jQv5p2/vU7HWhdw0TPrd/GY7AZyI1pE22nY1nayLmI/F2bOCcgJrsFB4fdePe7UF78t4nrEWxe9Ggg5p5/xvIrRjfxXedx2TrPJHwYUiIugg5YfxcpOF58M9rFnvvGYNjotzTfMLT4WIk=
